// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5kVvhs_2EX7mxjXvb0qkapUj55qP6_9c',
    appId: '1:709413519468:web:8c18e549d3834fa1ad9849',
    messagingSenderId: '709413519468',
    projectId: 'instagram-clone-e1e0e',
    authDomain: 'instagram-clone-e1e0e.firebaseapp.com',
    storageBucket: 'instagram-clone-e1e0e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpk67dQMJJW1fni5KC_b3XVORVP4lh-7U',
    appId: '1:709413519468:android:9a56392911abfefdad9849',
    messagingSenderId: '709413519468',
    projectId: 'instagram-clone-e1e0e',
    storageBucket: 'instagram-clone-e1e0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVCSj53lRm3cptXu9fJYMk9J6sfipIQkg',
    appId: '1:709413519468:ios:9d642528057a750dad9849',
    messagingSenderId: '709413519468',
    projectId: 'instagram-clone-e1e0e',
    storageBucket: 'instagram-clone-e1e0e.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );
}
